### ISSUE TITLE
Possible to use for heating AND cooling

### ISSUE THREAD

**Issue by terri1769** [cflurin/node-red-contrib-ramp-thermostat#10]
It seems like the thermostat is intended just for heating. Here where I live we have to run cooling part of the year as well. Can this be configured to do both?  If not currently can you add it as an enhancement request?  

Thanks so much for the hard work!

**Comment by cflurin** [comment]
Indeed the ramp-thermostat is designed for heating. However to control a cooling unit you could invert output 1 using a `change node`.

change node with an JSONata expression.
```js
[{
	"id": "d27d1df5.39cd2",
	"type": "change",
	"z": "6da90f72.dff58",
	"name": "",
	"rules": [{
		"t": "set",
		"p": "payload",
		"pt": "msg",
		"to": "payload ? false : true",
		"tot": "jsonata"
	}],
	"action": "",
	"property": "",
	"from": "",
	"to": "",
	"reg": false,
	"x": 620,
	"y": 100,
	"wires": [
		["a947c205.59da1"]
	]
}]
```

**Comment by pprotschka** [comment]
i think this would be equivalent to this!?

![image](https://user-images.githubusercontent.com/20007453/29491336-18647a46-8559-11e7-83d9-62b05292e90d.png)

**Comment by cflurin** [comment]
Almost, the JSONata expression just inverts the boolean value `true to false` or `false to true`.
