### ISSUE TITLE
Thermostat and MQTT

### ISSUE THREAD

**Issue by sjorsschiebergen** [cflurin/node-red-contrib-ramp-thermostat#13]
Hi there,

I have a problem with the combined usage of MQTT en the thermostat, my plan is to control each room in depend from each other. There will be 5 ESP8266 with an DHT22 sensor, and that publishing to MQTT is no problem, but no topics are the same. 

The topics for the thermostat are needing to be **setTarget** (I select that from an setpoint in HassIO) and **setCurrent**. 
How can i changes the topics from _Algemeen/Temperatuur (setCurrent)_ and _Algemeen/Temperatuur/setpoint (setTarget)_, to the specified topics for the thermostat to work. Also the profile is not really needed, cause i want to have an automated, manual and off function. 

Thx for the help!

Greetings,
Sjors

(English is not my native language, so don't grammer nazi me :P )

**Comment by cflurin** [comment]
Please, to get help go to:
https://groups.google.com/forum/#!forum/node-red
