### ISSUE TITLE
Output state does not trigger when within hysteresis

### ISSUE THREAD

**Issue by pcjlem** [cflurin/node-red-contrib-ramp-thermostat#15]
Recently I saw a strange effect when the `current temperature` is within the hysteresis, i.e. `(target temperature - hysteresis minus) <= current temperature <= (target temperature + hysteresis plus)`. In this case the `state` output does not seem to send its value, which leads to strange effects in connected nodes as they do not get a message at all.
My use case is quite standard where the `setCurrent` input gets its value from a temperate sensor every minute. Therefore, I would expect the `state` output to also send a message every minute, depending on target temperature, profile and hysteresis. 
It works as expected outside the hysteresis, i.e. in case that `current temperature < (target temperature - hysteresis minus)` or in case that `current temperature > (target temperature + hysteresis plus)`. Any idea what's happening?
Cheers pcjlem

**Comment by cflurin** [comment]
Correct, it works as coded. The zone between the low and high hysteresis is 
 a `deadband` that means there is no output.

Which strange effects did you see?

**Comment by pcjlem** [comment]
I have a chart behind the thermostat which visualises both the `current temperature` and the `state`. In case that Node Red is started (or restarted) while the temperature is within the deadband the effect is that the chart does _not_ display the state at all (as it does not even get an initial value). 

Looking into the code of `getState()` an easy solution could be to save the previous active state (`true` or `false`) in a new variable `prev_state` (with initial value `false`) each time that `state` is updated. This `prev_state` can then be returned as `state` while in the deadband. This way both "walking directions" through the deadband could be handled (upwards from below with `prev_state=true`, i.e. heating, or downwards from above with `prev_state=false`, i.e. not heating).
Only additional change would have to be an update of the status output to show the green ball instead of the grey circle in case that `prev_state == true`. This way the status display would also be more accurate as in fact the heating is on while "walking" through the deadzone from below, but currently the status is shown as off.

What do you think?

**Comment by cflurin** [comment]
I'll have a look at it, but just now I'm involved in another project.

So here is a workaround using the `dsm` node:
![ramp](https://user-images.githubusercontent.com/5056710/46071677-db0f7c80-c180-11e8-91cc-262ef1d4a573.png)

You need to install the `dsm` node and use the latest node-red version.
And to keep the state persistent, set the `contextStorage` in settings.js.

To set the dsm configuration click the `set` inject once, the dsm will retain the configuration even on node-red restart.

Flow:

```
[{"id":"c8aa34d0.546468","type":"ramp-thermostat","z":"6da90f72.dff58","name":"my room","profile":"7a5597f.52e6468","hysteresisplus":"1","hysteresisminus":"1","x":300,"y":740,"wires":[["896b3f99.69465"],["896b3f99.69465"],[]]},{"id":"40c5e2c6.52dc4c","type":"inject","z":"6da90f72.dff58","name":"","topic":"","payload":"22","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":720,"wires":[["c8aa34d0.546468"]]},{"id":"e431511d.23fcb","type":"inject","z":"6da90f72.dff58","name":"","topic":"","payload":"20","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":760,"wires":[["c8aa34d0.546468"]]},{"id":"9b646c99.755eb","type":"inject","z":"6da90f72.dff58","name":"","topic":"","payload":"18","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":800,"wires":[["c8aa34d0.546468"]]},{"id":"896b3f99.69465","type":"dsm","z":"6da90f72.dff58","name":"","sm_config":"","x":470,"y":740,"wires":[["bceadcb2.a2807"]]},{"id":"bceadcb2.a2807","type":"debug","z":"6da90f72.dff58","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":510,"y":680,"wires":[]},{"id":"ad609ad1.92ed78","type":"inject","z":"6da90f72.dff58","name":"set","topic":"set","payload":"{\"data\":{\"state\":null},\"methods\":{\"onTransition\":[\"if (typeof msg.payload === 'boolean') {\",\"   sm.data.state = msg.payload;\",\"} else {\",\"   msg.payload = sm.data.state;\",\"   output = true;\",\"}\"],\"status\":{\"fill\":{\"get\":\"sm.data.state ? 'green' : 'grey';\"},\"shape\":\"dot\",\"text\":{\"get\":\"sm.data.state\"}}}}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":310,"y":680,"wires":[["896b3f99.69465"]]},{"id":"7a5597f.52e6468","type":"profile","z":"","name":"dummy","time1":"00:00","temp1":"20","time2":"24:00","temp2":"20","time3":"","temp3":"","time4":"","temp4":"","time5":"","temp5":"","time6":"","temp6":"","time7":"","temp7":"","time8":"","temp8":"","time9":"","temp9":"","time10":"","temp10":""}]
```

**Comment by cflurin** [comment]
@pcjlem,

I've uploaded a new version, supporting pre_state as discussed.
