### ISSUE TITLE
What electromagnetic valve works with MQTT?

### ISSUE THREAD

**Issue by iChUdY** [cflurin/node-red-contrib-ramp-thermostat#16]
Hello,

@cflurin this node is easy implement to HomeKit via homebridge-mqtt and works perfect, but i stuck on control just my boiler for whole house. 

I read that you use an electromagnetic valve for each room. Could you please advise what type?

I will then like to share my way of implementation on six rooms. 

Thanks.

**Comment by cflurin** [comment]
I use 24V danfoss valves (we have a floor heating on 2 floors, total 7 rooms)

http://products.danfoss.com/productrange/list/heatingsolutions/floor-heating-hydronics/twa-standard-actuators/#/

They are controlled from node-red via two old enOcean actuators (on/off) with 4 outputs each, but you can use other actuators or an ESP8266.
Probably today I'd take two ESP8266 plus a 4-Channel Relay module.
If you take the ESPEasy firmware, you can control the valves using MQTT.

**Comment by iChUdY** [comment]
@cflurin thanks 👌🏻

**Comment by iChUdY** [comment]
Hi,

I bought five **MAX! Radiator Thermostat**
http://www.eq-3.com/products/max/max-house-solution/max-radiator-thermostat.html 
with **MAX! Cube LAN Gateway**. 

Very easy control with node-red-contrib-maxcube2.
https://flows.nodered.org/node/node-red-contrib-maxcube2

So currently i have five radiator valve and one boiler. Boiler is switched with OR function from five node-red-contrib-ramp-thermostat state. Radiator valves sets from target, but only if state is 1. If state is 0 then valve set to 17°C. 

**This is results:**

![262a7984-8b4f-434c-a56d-bb694ec3ca1d](https://user-images.githubusercontent.com/11601525/47272264-78dd4800-d583-11e8-8be8-4417283311b8.jpeg)
![3f8432c4-3b0c-4025-8a9e-c388b75b3c99](https://user-images.githubusercontent.com/11601525/47272265-7975de80-d583-11e8-91b7-a1471b95eea1.jpeg)

**Of course all implement to HomeKit via homebridge-mqtt:**

![3d97c9e7-b7d8-4ad0-9db1-9173c08b50f5](https://user-images.githubusercontent.com/11601525/47272392-45032200-d585-11e8-8a06-67dfc871553a.jpeg)
![4baff6d2-fe07-46af-8058-f465b05fd08e](https://user-images.githubusercontent.com/11601525/47272393-45032200-d585-11e8-8bfd-693b93e28a62.jpeg)
![e179daad-d2a4-4b5a-b005-826e5c2ed518](https://user-images.githubusercontent.com/11601525/47272394-459bb880-d585-11e8-8b34-8518d73687c3.jpeg)
