### ISSUE TITLE
Incorrect time

### ISSUE THREAD

**Issue by iChUdY** [cflurin/node-red-contrib-ramp-thermostat#17]
Hi,

my timezone on RaspberryPi is Czech Republic Prague UTC+2

<img width="212" alt="snimek obrazovky 2018-10-02 v 14 59 16" src="https://user-images.githubusercontent.com/11601525/46350020-f03e4c80-c653-11e8-9bff-49136860b838.png">

ramp-thermostat node switching in incorrect time viz screenshot...

![img_0601](https://user-images.githubusercontent.com/11601525/46350126-398e9c00-c654-11e8-98a7-7e657acfcdb8.jpeg)
![img_0598](https://user-images.githubusercontent.com/11601525/46350144-414e4080-c654-11e8-8492-b0dfda3b2d5a.jpeg)
![img_0599](https://user-images.githubusercontent.com/11601525/46350145-41e6d700-c654-11e8-9d13-baba7767faae.jpeg)
![img_0600](https://user-images.githubusercontent.com/11601525/46350146-41e6d700-c654-11e8-9556-6b42f44bc108.jpeg)

**Comment by cflurin** [comment]
Strange, it shouldn't, the ramp-thermostat uses Date().

Try this flow and post what you get:

```
[{"id":"bae429e2.64e498","type":"function","z":"cf6706ec.415a58","name":"","func":"msg.payload = new Date();\n\nreturn msg;","outputs":1,"noerr":0,"x":270,"y":2620,"wires":[["1ac21ef9.332ec1"]]},{"id":"1ac21ef9.332ec1","type":"debug","z":"cf6706ec.415a58","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":430,"y":2620,"wires":[]},{"id":"add46b9a.c51008","type":"inject","z":"cf6706ec.415a58","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":120,"y":2620,"wires":[["bae429e2.64e498"]]}]
```

**Comment by iChUdY** [comment]
Hi,
return 

>  "Tue Oct 02 2018 16:27:31 GMT+0000 (UTC)"

actually now 18:27:31

> root@raspberrypi:~# date

> Tue 2 Oct 18:27:55 CEST 2018

**Comment by cflurin** [comment]
Something is different, I get:
```
"Tue Oct 02 2018 19:01:23 GMT+0200 (CEST)"
```

```
$ date
Tue Oct  2 19:00:49 CEST 2018
```

I don't now why, you might ask in the node-red-forum.

**Comment by iChUdY** [comment]
I'm researching the internet and I'm not the only one with this problem. 
So far I have found one thing:

new Date(); returned "Tue Oct 02 2018 17:05:45 GMT+0000 (UTC)"

new Date().toLocaleString(); returned "2018-10-2 19:05:45"

<img width="300" alt="snimek obrazovky 2018-10-02 v 19 11 08" src="https://user-images.githubusercontent.com/11601525/46364862-47a1e400-c677-11e8-8167-29601f33e786.png">

**Comment by iChUdY** [comment]
Ok. I found solution.

Add 

> process.env.TZ = "Europe/Prague"; 

to setting.js in node-red.

<img width="300" alt="snimek obrazovky 2018-10-02 v 19 24 02" src="https://user-images.githubusercontent.com/11601525/46365383-c3506080-c678-11e8-97b3-cf2309ce443b.png">

**Comment by cflurin** [comment]
There is no such setting in my `settings.js`. Anyway it's okey.

**Comment by ran85** [comment]
Hey. I think this is a real issue. `new Date()` always  runs on UTC.  Looks like node-red is returning UTC even if a simple node process returns system timezone.  Am I missing something ?

**Comment by cflurin** [comment]
Nope, this is a NR setting. Search in the NR-Forum for `UTC` or aks for help in the Forum

**Comment by ran85** [comment]
Cool. Thanks .
