### ISSUE TITLE
Weekly schedule for each room

### ISSUE THREAD

**Issue by iChUdY** [cflurin/node-red-contrib-ramp-thermostat#18]
Hi,

for weeks now, I have been fully involved in building smart home heating. This knot is perfect for my use and greatly facilitates my work. Now I have one boiler and five controlled valves in five rooms. My goal is to create a fully automated schedule specific to each day of the week for each room separately. All of this, of course, connected to Homebridge for the possible manual setting of each room according to the needs or location of family members. 

For HomeKit support I use:
TargetTemperature for setTarget: msg.payload ["value"];
TargetHeatingCoolingState0 for SetTarget: 17; 
TargetHeatingCoolingState1 (Heating) for setTarget: 30; 
TargetHeatingCoolingState2 (Cooling) for setTarget: 17; 
TargetHeatingCoolingState3 (Auto) for setProfilet: room_name;

Everything works perfectly, but TargetHeatingCoolingState3 (Auto) for setProfilet: room_name, there is a problem that always sets only a profile for a particular room and not a given day.

I know this could be solved using several nodes using the date function and the like, but I'm convinced that a much better solution is to set a full weekly profile directly in the ramp_node.

What do you think?

**Comment by cflurin** [comment]
Generally this can be achieved using setProfile e.g. one profile for the workdays and one for the weekend. 
I don't have any plan to add week profiles and I would like to keep this node as simple as possible.

**Comment by iChUdY** [comment]
Ok it makes sense.
