### ISSUE TITLE
Error message when using the node

### ISSUE THREAD

**Issue by patwiken** [cflurin/node-red-contrib-ramp-thermostat#19]
Hi,
I have just found your node red ramp thermostat but I have an error message when the node is running. I only inject the two topics: setCurrent and setProfile.

28/10/2018 à 21:23:22node: Thermostat radiateur
msg : error
"TypeError: Cannot read property 'toFixed' of undefined"

What is this error?

**Comment by cflurin** [comment]
Hi,
Could you export your flow and upload it her, I'll have a look.

**Comment by patwiken** [comment]
Thank you for your quick answer.
The flow is here after:

[{"id":"8176f2c2.5056e","type":"ramp-thermostat","z":"2328a339.f0e8bc","name":"Thermostat radiateur","profile":"c3ca1135.a79a3","hysteresisplus":"1","hysteresisminus":"1","x":663,"y":226.5,"wires":[["4826fa72.0c7e24"],["c3ab495c.da3eb8"],["200db826.bca498","b228e16f.e87ac"]]},{"id":"c3ab495c.da3eb8","type":"ui_text","z":"2328a339.f0e8bc","group":"650b6065.13bd5","order":2,"width":0,"height":0,"name":"Température mesurée","label":"Température mesurée","format":"{{msg.payload}}","layout":"row-spread","x":952,"y":189,"wires":[]},{"id":"4826fa72.0c7e24","type":"ui_text","z":"2328a339.f0e8bc","group":"650b6065.13bd5","order":3,"width":0,"height":0,"name":"Actionneur","label":"Actionneur","format":"{{msg.payload}}","layout":"row-spread","x":931,"y":95,"wires":[]},{"id":"200db826.bca498","type":"ui_text","z":"2328a339.f0e8bc","group":"650b6065.13bd5","order":1,"width":0,"height":0,"name":"Consigne","label":"Consigne","format":"{{msg.payload}}","layout":"row-spread","x":915,"y":267,"wires":[]},{"id":"b228e16f.e87ac","type":"debug","z":"2328a339.f0e8bc","name":"Consigne","active":true,"console":"false","complete":"payload","x":921,"y":339,"wires":[]},{"id":"6e2b2d8a.fe61b4","type":"inject","z":"2328a339.f0e8bc","name":"","topic":"setProfile","payload":"Semaine","payloadType":"str","repeat":"","crontab":"","once":true,"x":376,"y":176,"wires":[["8176f2c2.5056e"]]},{"id":"f503128.40b3cf","type":"inject","z":"2328a339.f0e8bc","name":"","topic":"setCurrent","payload":"20","payloadType":"num","repeat":"","crontab":"","once":true,"x":342,"y":232,"wires":[["8176f2c2.5056e"]]},{"id":"c3ca1135.a79a3","type":"profile","z":"","name":"Semaine","time1":"00:00","temp1":"16","time2":"07:00","temp2":"20","time3":"12:00","temp3":"18","time4":"17:00","temp4":"20","time5":"","temp5":"","time6":"","temp6":"","time7":"","temp7":"","time8":"","temp8":"","time9":"","temp9":"","time10":"","temp10":""},{"id":"650b6065.13bd5","type":"ui_group","z":"","name":"Thermostat","tab":"2cc5c575.d22c6a","disp":true,"width":"6","collapse":false},{"id":"2cc5c575.d22c6a","type":"ui_tab","z":"","name":"Maison","icon":"dashboard"}]

**Comment by cflurin** [comment]
**A Profile has at least 2 Points and should typically start at 00:00 and end at 24:00.**

In your profile `Semaine` add the last point `24:00` `20` or what you need.

**Comment by patwiken** [comment]
Thanks for your reply. It's OK. Your node seems to be very nice but perhaps a little more explanation or examples in the documentation could be interesting.
Thanks

**Comment by cflurin** [comment]
> Thanks for your reply. It's OK. Your node seems to be very nice but perhaps a little more explanation or examples in the documentation could be interesting.
> Thanks

Well, this is `open source`, that means that you can use the software free!
I've spent resources and time for development and docs and I also provide support free!

First step a new user should do is to read the doc (README) and the info provided in the info panel.

But feel free to upload your examples to the wiki.
