### ISSUE TITLE
profile input

### ISSUE THREAD

**Issue by titpoulet** [cflurin/node-red-contrib-ramp-thermostat#2]
As you ask me :) i post my demand on Github 

It's possible to have a input for setpoint temperature or import a profile via a json variable?

In your next version :)

**Comment by marksev1** [comment]
I'm also interested in that, it would be cool if there was an example also on how to use it with the dashboard to interactivly set the profile and the setpoint temperature. Can it be expanded to multiple temperatures per times of the day :)?

**Comment by cflurin** [comment]
Hi,
I've just uploaded a new version.
Please install from GitHub:

```
npm install cflurin/node-red-contrib-ramp-thermostat
```
1. define so many profiles as you like in edit ramp-thermostat > add new profile... e.g.
   standard, comfort, eco, holiday etc.
2. select the profile e.g. using a function node wired to the input of ramp-thermostat:

```
var msg1 = {};
msg1.profile = "comfort";
return msg1;
```

**Comment by marksev1** [comment]
Very cool cflurin! So the weekday, weekend handling I'd still have to do inside the function node?

**Comment by cflurin** [comment]
Hi all: new version on GitHub.

@marksev1:
the criteria for setting a new profile is numerous. I think the best is to let the user decide how to set the profile. You can do it using a function node or other build in nodes such as the inject node (at a specific time) and select the days you need.

**Comment by marksev1** [comment]
Can we go over it again it seems I have a bit hard head :)... From the dashboard now only profiles could be choosen right? As you said: standard, comfort, eco, holiday, weekdays, weekends.  What about just the override temperature setpoint, if I'd have a rotary encoder + mqtt for setting thermostat setpoint manually. Would that be allowed? And then next day again back to old profile?

**Comment by cflurin** [comment]
ops! I clicked the wrong button I'll come back soon.

**Comment by cflurin** [comment]
Sure it would be possible to add this option but this isn't the concept of ramp-thermostat. It works with profiles for a timespan of 24 hours.

In this example you see two lines: the actual and the target temperatures
![ramp-thermostat3](https://cloud.githubusercontent.com/assets/5056710/19418689/3eeef380-93c9-11e6-96a6-5809d109525a.jpg)

The profile is defined using 6 points:

time   | temp
00:00 | 18.0
03:00 | 18.0
06:00 | 20.5
18:00 | 20.5
20:00 | 18.0
24:00 | 18.0

Every time the input is triggered (e.g. interval = 15 min) with the actual temperature ramp-thermostat compares the actual temperature with the calculated target temperature and set the state (output 1) to true or false.

Is it so far clear?

**Comment by marksev1** [comment]
Yes I understand this, but what about if someone feels cold even at your set temperature, then either change profile to one with higher temperature or manually set a temperature? (would be still nice to be able to manually set temperature).

**Comment by cflurin** [comment]
Well I can add an input `msg.target`, the target will be constant until a new msg.target or a msg.profile is sent again or until node-red is restarted. That means if you set the temperature manually, you have to "reset" it manually.

**Comment by marksev1** [comment]
That could be a good idea yes

**Comment by cflurin** [comment]
new version 0.2.0 on GitHub.

```
npm install cflurin/node-red-contrib-ramp-thermostat
```

I changed the runtime settings, now using topic `setProfile` and `setTarget`. This will simplify the handling as you can use an inject node directly.
It would be nice if you could test the new version, feedback welcome.

**Comment by marksev1** [comment]
Thanks for adding all my wishes! You are a great developer! :) I will try my best to test it, but maybe will ask you for some more info on slack :).

**Comment by cflurin** [comment]
slack is ok for me :-)

**Comment by titpoulet** [comment]
Dear,

Thank for your developping !!! :)
But since your last version, i have an error : 
msg : error
Error: Invalid property expression: unexpected ' ' at position 4

Have you an idea ?

Thank you for your help !!!

**Comment by cflurin** [comment]
@titpoulet:
Could you please upload your node-red flow (select, export>clipboard and copy past here).
I' ll try to reproduce the error on my test-system.

**Comment by titpoulet** [comment]
`[{"id":"ee8832bc.e2c5f","type":"inject","z":"3abc3b78.c7f144","name":"","topic":"","payload":"","payloadType":"date","repeat":"5","crontab":"","once":true,"x":75,"y":203,"wires":[["1fda856.4c5847b"]]},{"id":"1fda856.4c5847b","type":"ownet-read","z":"3abc3b78.c7f144","owserver":"8cc9e46b.da2788","path":"/28.FFAD616A1404","subpath":"/temperature","name":"","x":305,"y":206,"wires":[["83762de8.1ab3d"]]},{"id":"83762de8.1ab3d","type":"ramp-thermostat","z":"3abc3b78.c7f144","name":"temp bureau","profile":"5b482a71.9bcd54","x":538,"y":209.5,"wires":[["fcbac5e4.bc7fc8"],["9731653d.9df9f8","c2e36cf5.fd3b8"],["4b4bc77c.1d98d8","c2e36cf5.fd3b8"]]},{"id":"9731653d.9df9f8","type":"ui_gauge","z":"3abc3b78.c7f144","name":"","group":"b10c5cae.4a42","order":0,"width":0,"height":0,"gtype":"gage","title":"Bureau","label":"°C","format":"{{value}}","min":0,"max":"30","x":725,"y":245,"wires":[]},{"id":"4b4bc77c.1d98d8","type":"ui_text","z":"3abc3b78.c7f144","group":"3df6fac3.9783e6","order":0,"width":0,"height":0,"name":"","label":"consigne","format":"{{msg.payload}}","layout":"row-spread","x":734,"y":200,"wires":[]},{"id":"c2e36cf5.fd3b8","type":"ui_chart","z":"3abc3b78.c7f144","group":"3df6fac3.9783e6","order":0,"width":0,"height":0,"label":"chart","name":"","interpolate":"linear","nodata":"","ymin":"","ymax":"","removeOlder":1,"removeOlderUnit":"3600","x":721,"y":281,"wires":[[],[]]},{"id":"8cc9e46b.da2788","type":"owserver","z":"3abc3b78.c7f144","host":"localhost","port":"4304"},{"id":"5b482a71.9bcd54","type":"profile","z":"3abc3b78.c7f144","name":"test","time1":"00:00","temp1":"25","time2":"01:00","temp2":"24","time3":"10:00","temp3":"25","time4":"11:11","temp4":"11","time5":"","temp5":"","time6":"","temp6":"","time7":"","temp7":"","time8":"","temp8":"","time9":"","temp9":"","time10":"","temp10":""},{"id":"b10c5cae.4a42","type":"ui_group","z":"","name":"Temperature","tab":"2ec0b148.40224e","order":2,"disp":true,"width":"6"},{"id":"3df6fac3.9783e6","type":"ui_group","z":"","name":"Graphique","tab":"2ec0b148.40224e","order":1,"disp":true,"width":"14"},{"id":"2ec0b148.40224e","type":"ui_tab","z":"3abc3b78.c7f144","name":"Graph","icon":"dashboard"}]`

**Comment by cflurin** [comment]
@titpoulet:
Thanks for your feedback. There is an issue with the ramp-thermostat name.
Please change your name from `temp bureau` to `temp_bureau`, also without space.
I'll upload a new version soon to fix it.

**Comment by cflurin** [comment]
new version 0.2.1 available.

**Comment by titpoulet** [comment]
Dear,

I updated your module and change the name from temp bureau to temp_bureau, but it doesn't work correctly...
When i run the system, i have the error => msg: string [13] invalid topic.

In input, i have un numeric input with dashboard and 1-wire module for temperature sensor.

`[{"id":"ee8832bc.e2c5f","type":"inject","z":"3abc3b78.c7f144","name":"","topic":"","payload":"","payloadType":"date","repeat":"5","crontab":"","once":true,"x":75,"y":203,"wires":[["1fda856.4c5847b"]]},{"id":"1fda856.4c5847b","type":"ownet-read","z":"3abc3b78.c7f144","owserver":"8cc9e46b.da2788","path":"/28.FFAD616A1404","subpath":"/temperature","name":"","x":322,"y":203,"wires":[["83762de8.1ab3d"]]},{"id":"83762de8.1ab3d","type":"ramp-thermostat","z":"3abc3b78.c7f144","name":"temp","profile":"27084ac3.f1e4f6","x":552,"y":213.5,"wires":[["fcbac5e4.bc7fc8"],["9731653d.9df9f8"],["4b4bc77c.1d98d8"]]},{"id":"9731653d.9df9f8","type":"ui_gauge","z":"3abc3b78.c7f144","name":"","group":"b10c5cae.4a42","order":0,"width":0,"height":0,"gtype":"gage","title":"Bureau","label":"°C","format":"{{value}}","min":0,"max":"30","x":738,"y":201,"wires":[]},{"id":"4b4bc77c.1d98d8","type":"ui_text","z":"3abc3b78.c7f144","group":"3df6fac3.9783e6","order":0,"width":0,"height":0,"name":"","label":"consigne","format":"{{msg.payload}}","layout":"row-spread","x":746,"y":242,"wires":[]},{"id":"41014106.e9e25","type":"ui_numeric","z":"3abc3b78.c7f144","group":"3df6fac3.9783e6","order":0,"width":0,"height":0,"name":"","label":"setTarget","topic":"","format":"{{value}}","min":0,"max":10,"x":386,"y":267,"wires":[["83762de8.1ab3d"]]},{"id":"8cc9e46b.da2788","type":"owserver","z":"3abc3b78.c7f144","host":"localhost","port":"4304"},{"id":"27084ac3.f1e4f6","type":"profile","z":"3abc3b78.c7f144","name":"profile","time1":"00:00","temp1":"25","time2":"","temp2":"","time3":"","temp3":"","time4":"","temp4":"","time5":"","temp5":"","time6":"","temp6":"","time7":"","temp7":"","time8":"","temp8":"","time9":"","temp9":"","time10":"","temp10":""},{"id":"b10c5cae.4a42","type":"ui_group","z":"","name":"Temperature","tab":"2ec0b148.40224e","order":2,"disp":true,"width":"6"},{"id":"3df6fac3.9783e6","type":"ui_group","z":"","name":"Graphique","tab":"2ec0b148.40224e","order":1,"disp":true,"width":"14"},{"id":"2ec0b148.40224e","type":"ui_tab","z":"3abc3b78.c7f144","name":"Graph","icon":"dashboard"}]`

**Comment by cflurin** [comment]
Hi,

I don't have installed the node ownet (owserver)
could you please upload a flow without ownet (owserver), just use inject.

and if possible without ui_\* nodes, just use inject for input and debug for output.

**Comment by cflurin** [comment]
@titpoulet:
Okay I see the reason:
In your ui_numeric node you have to define the topic: setTarget. Take a look at README.

**Comment by titpoulet** [comment]
@cflurin 

Thank for your help, i seen my first error on uinumeric node. It's solved. My target input work !!! :)
I find th error, the ownet read node output is a string format !!! 
I must convert string => number to do running correctly your thermostat !!! 
It's work now !!!!

Thank you

I will be back with my project of automation for my home if you want

**Comment by cflurin** [comment]
@titpoulet 
great! If you like, you can upload your project, just open an issue e.g. "my project".

**Comment by titpoulet** [comment]
@cflurin 
In your next version, could you include a shedule with day? I explain: 
- from monday to friday we can have program 1
- from sunday to saturday program 2

We can have different program beetwen week and weekend...

**Comment by cflurin** [comment]
@titpoulet:
this can be done with a simple inject node.

![scheduler](https://cloud.githubusercontent.com/assets/5056710/21043131/bceb426a-bdf5-11e6-811d-f9f38e8a7253.png)

```sh
[{"id":"dcf1c1af.13e9","type":"ramp-thermostat","z":"cb9d9d67.14ab3","name":"","profile":"220b4e45.5e2212","hysteresisplus":0,"hysteresisminus":0,"x":410,"y":1720,"wires":[[],[],[]]},{"id":"a8c74323.24129","type":"inject","z":"cb9d9d67.14ab3","name":"","topic":"setProfile","payload":"weekend","payloadType":"str","repeat":"","crontab":"01 00 * * 6,0","once":false,"x":140,"y":1740,"wires":[["dcf1c1af.13e9"]]},{"id":"69174502.8d692c","type":"inject","z":"cb9d9d67.14ab3","name":"","topic":"setProfile","payload":"weekday","payloadType":"str","repeat":"","crontab":"01 00 * * 1,2,3,4,5","once":false,"x":140,"y":1700,"wires":[["dcf1c1af.13e9"]]},{"id":"220b4e45.5e2212","type":"profile","z":"","name":"weekend","time1":"00:00","temp1":"21.0","time2":"24:00","temp2":"21.0","time3":"","temp3":"","time4":"","temp4":"","time5":"","temp5":"","time6":"","temp6":"","time7":"","temp7":"","time8":"","temp8":"","time9":"","temp9":"","time10":"","temp10":""}]
```
