### ISSUE TITLE
Feature request: Support weekdays

### ISSUE THREAD

**Issue by tedstriker** [cflurin/node-red-contrib-ramp-thermostat#20]
Hi there,

it would be nice if profiles would support weekday-dependent configuration.
e.g. On weekends people tend to be more at home, which results in a different heating pattern.

**Comment by cflurin** [comment]
Have a look here: https://github.com/cflurin/node-red-contrib-ramp-thermostat/issues/18

**Comment by tedstriker** [comment]
Perfect! Thank you ;)
