### ISSUE TITLE
I set the target temperature to whole numbers, but get 0.7 added to it

### ISSUE THREAD

**Issue by cooljimy84** [cflurin/node-red-contrib-ramp-thermostat#24]
I've set my temps to whole numbers.
12:00 AM 20
06:00 AM 21
08:00 AM 22
05:30 PM 23
07:00 PM 24
11:59 PM 25
Hysteresis + is 0
Hysteresis - is 0
However when i send (using inject the item) the msg.payload with 22, i get in my debug,
state: True
current: 22
target 22.7 (tho it's really set to 22 in the profile)

**Comment by cflurin** [comment]
@cooljimy84,

Could you please export your flow (compact) and post it here, I'll have a look.

**Comment by cooljimy84** [comment]
Just moved it to a flow on its own and it's now 0.8 above ....

**Comment by cooljimy84** [comment]
[{"id":"4f299257.b8d744","type":"ramp-thermostat","z":"6afe6b2e.984654","name":"","profile":"f83d38cd.f9d658","hysteresisplus":"0","hysteresisminus":"0","x":170,"y":100,"wires":[["6ce162ef.1f00dc"],["6ce162ef.1f00dc"],["d3554d27.9f6","6ce162ef.1f00dc"]]},{"id":"6ce162ef.1f00dc","type":"debug","z":"6afe6b2e.984654","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":580,"y":80,"wires":[]},{"id":"caef6803.c2cdc","type":"inject","z":"6afe6b2e.984654","name":"","topic":"","payload":"22","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":110,"y":40,"wires":[["4f299257.b8d744"]]},{"id":"d3554d27.9f6","type":"change","z":"6afe6b2e.984654","name":"Set ramptemp","rules":[{"t":"set","p":"ramptemp","pt":"flow","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":380,"y":140,"wires":[[]]},{"id":"f83d38cd.f9d658","type":"profile","z":"","name":"Weekday","time1":"00:00","temp1":"20","time2":"06:00","temp2":"21","time3":"08:00","temp3":"22","time4":"17:30","temp4":"23","time5":"19:00","temp5":"24","time6":"23:59","temp6":"25","time7":"","temp7":"","time8":"","temp8":"","time9":"","temp9":"","time10":"","temp10":""}]

**Comment by cflurin** [comment]
Your profile Weekday:

![weekday](https://user-images.githubusercontent.com/5056710/49231556-7d064c00-f3f2-11e8-84e8-84db5e5fedc5.png)

So e.g. at 16:20 the target is 22.8

You have to change your profile.

**Comment by cooljimy84** [comment]
RIGHT !
Totally didn't get it RAMPs up the the temperature !
:man_facepalming: 

I suspect i would have to use something different if i wanted a hard change at 06:00 08:00 etc...

**Comment by cflurin** [comment]
Try this:

![weekday1](https://user-images.githubusercontent.com/5056710/49232612-914b4880-f3f4-11e8-8d54-0cfaaf5003d6.png)

**Comment by cooljimy84** [comment]
Kool, will need more than 10 points then, or ramp at curtain points to save entries.

I'll mark this as closed tho. Sorry for not even reading the title of the right.
