### ISSUE TITLE
Feature request: More than 10 entries 

### ISSUE THREAD

**Issue by cooljimy84** [cflurin/node-red-contrib-ramp-thermostat#25]
Nothing more than that, just my use case where i have used up all 10, and would like more if it's an easy win.

**Comment by cflurin** [comment]
How many points (entries) would you need?
Could you be a bit more specific about your use case?

**Comment by cooljimy84** [comment]
I was the guy that didn't read that this ramped up between the two temperature points. So I took your example and have two points of every temperature, to get a more square graph ( and less ramp )

I was wondering if it was possible to have more than 10 points, as in my use case I'm doubling up my entries to make the more hard cut points

**Comment by cflurin** [comment]
See [Profile-with-more-than-10-points](https://github.com/cflurin/node-red-contrib-ramp-thermostat/wiki/Profile-with-more-than-10-points)

**Comment by cooljimy84** [comment]
Awesome,
i suspect i could also have more profiles, with 12 hours (making sure i have a start at 00:00 and end 23:59) but all the points in the first 12 hours, then another with more points in the second 12 hours.
