### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by coffeepoweredteacher** [cflurin/node-red-contrib-ramp-thermostat#28]
Hi,

Super work on this, such a great node. 
I had a previously working node-red setup with your ramp thermostat and a Function node. Unfortunately, I decided to update the OS and since updating and re-importing my flows, I have been unable to get the previous setup to work. 

Forgive me if my code is an awful mess!
Basically, the function node checks if the mode is 'Summer or Winter[mode=true/false]' then if the Target temp is '12' or '7'. It then passes on the global.temp as the payload and sets the msg.topic so that I can change the profile on your Ramp Thermostat. Unfortunately, whenever I have the function node before the Ramp Thermostat, I get the error: TypeError: Cannot read property 'toLowerCase' of undefined.

![ramp thermostat 2](https://user-images.githubusercontent.com/21358106/52981250-5a267b00-33d6-11e9-905a-501cbba1db4f.JPG)

If I add a Inject node to manually inject global.temp as the msg.payload it works fine. If I directly connect the Temp output from my C temp program, it works fine. But going through the Function I'm having problems. Adding a debug node reveals it's passing on the temp as expected (nothing strange). 

Again, apologies if it's my horrible coding that has caused this, but thought it was worth reporting for you to look into? 

![ramp thermostat1](https://user-images.githubusercontent.com/21358106/52981246-55fa5d80-33d6-11e9-89f2-df87fd88a088.JPG)

**Comment by cflurin** [comment]
Hi,

In your function you build an new object `tempMSG` without topic!

Add topic:
```
var tempMSG = {
    "topic": "setCurrent",
    "payload": temp
}
```

or at least:

```
var tempMSG = {
    "topic": "",
    "payload": temp
}
```

**Comment by coffeepoweredteacher** [comment]
Thanks for the help! That was indeed the problem.

Much appreciated.
