### ISSUE TITLE
Questions and improvements

### ISSUE THREAD

**Issue by syoma755** [cflurin/node-red-contrib-ramp-thermostat#3]
Hi there, 
Sorry I don't know where to ask. 
I have a flow with thermostat function - which does more or less the same thing:
![thermostat](https://cloud.githubusercontent.com/assets/18278130/19529624/0e27855e-9631-11e6-997e-9b4855bbb39b.png)

In my next plans are:
- use google calendar input to make schedules
- use a kind of PID controller.

I wonder if I could use your function for this. Currently I see you have no hysteresis. Is it possible to add?

**Comment by cflurin** [comment]
Hi syoma755:
Here is the perfect place to ask.

Basically the ramp-thermostat is a simple PID controller only with the Proportional term. Heating systems used in buildings are quite slow, that means when the actuator turns off there is always an overshooting, therefore I have no hysteresis. But I'll add this to my todo list, maybe this is useful for electrical heating systems or for other purpose.

The ramp-thermostat is similar to a profile controller. During 24 hours you can schedule the target temperature (setpoint) as you like.
For other scenes you can select or set a profile depending on your needs (away, holiday, party, etc.).

**Comment by syoma755** [comment]
You are right about overshoot - I have an underfloor water heating and it's there. But I wonder if absence of hysteresis would create oscillations. In my case with 0.3° Hysteresis I have about 0.5° oscillation. I will check how low it would be if I remove hysteresis totally. 
Anyway adding integrator/differentiator + weather compensation would be interesting. 
When it would be self-learning, like Nest - that' would be really great.

**Comment by cflurin** [comment]
I think there is no need for a PID controller, I have also an underfloor water heating and this is very slow.

Well the node has already a weather compensation. Take a look a the images in the samples.
The ramp (gradient line) in the morning has the property to turn on the heating depending on the measured temperature. Let's say in the night it's cold or very cold so in the morning the room temperature will be lower an the heating will turn on earlier.
BTW my central heating flow temperature is quite low (ca 30 °C) and I have a "single room temperature control " for almost all rooms. That means I use a temperature sensor and an actuator for the water valve for each room.

**Comment by syoma755** [comment]
I tested without hysteresis - it seems required in my case. I measure temperature every minute, and when it close to setpoint it starts to generate multiple switchings at crossing. I have a relay on actuators, so it is not nice sound.

**Comment by cflurin** [comment]
You could test the  ramp-thermostat and try this approach:

take output 2 (c: current) and 3 (t: target) and compare them including h: hysteresis.

if (c < (t-h)) heating = on
if (c >( t+h)) heating = off

If this works for you, the next step will be to add the hysteresis to the ramp-thermostat config.

**Comment by cflurin** [comment]
@syoma755:
I added the hysteresis in the last version. Please install from GitHub:

``` sh
sudo npm install cflurin/node-red-contrib-ramp-thermostat
```

It'd be nice if you could test it.

**Comment by maragelis** [comment]
Hi thanks for the good work, I would like if there was a power option, say a topic for power on/off. I am using this with homebridge and would like to send on/off commands. Thanks a lot

**Comment by cflurin** [comment]
@maragelis: to clarify: what should the thermostat do at power=off?
no msg to output 1 (state)?
Otherwise you can do it with node-red:
![thermostat](https://cloud.githubusercontent.com/assets/5056710/20866089/d5285dca-ba23-11e6-8fc2-0264d82ca7ab.png)

```sh
[{
	"id": "e31eaa38.753d58",
	"type": "ramp-thermostat",
	"z": "cb9d9d67.14ab3",
	"name": "",
	"profile": "27e08827.273fb8",
	"hysteresisplus": 0,
	"hysteresisminus": 0,
	"x": 290,
	"y": 860,
	"wires": [
		["56c3c38b.31b1ec"],
		[],
		[]
	]
}, {
	"id": "56c3c38b.31b1ec",
	"type": "switch",
	"z": "cb9d9d67.14ab3",
	"name": "",
	"property": "thermostat",
	"propertyType": "global",
	"rules": [{
		"t": "cont",
		"v": "on",
		"vt": "str"
	}],
	"checkall": "true",
	"outputs": 1,
	"x": 450,
	"y": 840,
	"wires": [
		["45e64a2.230f4b4"]
	]
}, {
	"id": "d18166b6.18dd98",
	"type": "inject",
	"z": "cb9d9d67.14ab3",
	"name": "Fake t=19.0",
	"topic": "",
	"payload": "19.0",
	"payloadType": "num",
	"repeat": "",
	"crontab": "",
	"once": false,
	"x": 110,
	"y": 860,
	"wires": [
		["e31eaa38.753d58"]
	]
}, {
	"id": "45e64a2.230f4b4",
	"type": "debug",
	"z": "cb9d9d67.14ab3",
	"name": "",
	"active": true,
	"console": "false",
	"complete": "false",
	"x": 590,
	"y": 840,
	"wires": []
}, {
	"id": "dd3f662.5e6f798",
	"type": "mqtt in",
	"z": "cb9d9d67.14ab3",
	"name": "",
	"topic": "homebridge/from/set",
	"qos": "2",
	"broker": "c627c6eb.dbd8a8",
	"x": 120,
	"y": 780,
	"wires": [
		["a7736a7a.eab1d8"]
	]
}, {
	"id": "ba3bcacb.c45d38",
	"type": "function",
	"z": "cb9d9d67.14ab3",
	"name": "set on/off",
	"func": "if (msg.payload.value) {\n    global.set(\"thermostat\", \"on\");\n} else {\n    global.set(\"thermostat\", \"off\");\n}\n\nreturn msg;",
	"outputs": 1,
	"noerr": 0,
	"x": 420,
	"y": 780,
	"wires": [
		["18666727.de2129"]
	]
}, {
	"id": "18666727.de2129",
	"type": "debug",
	"z": "cb9d9d67.14ab3",
	"name": "",
	"active": true,
	"console": "false",
	"complete": "false",
	"x": 570,
	"y": 780,
	"wires": []
}, {
	"id": "a7736a7a.eab1d8",
	"type": "json",
	"z": "cb9d9d67.14ab3",
	"name": "",
	"x": 290,
	"y": 780,
	"wires": [
		["ba3bcacb.c45d38"]
	]
}, {
	"id": "27e08827.273fb8",
	"type": "profile",
	"z": "",
	"name": "living_room",
	"time1": "00:00",
	"temp1": "20.0",
	"time2": "24:00",
	"temp2": "20.0",
	"time3": "",
	"temp3": "",
	"time4": "",
	"temp4": "",
	"time5": "",
	"temp5": "",
	"time6": "",
	"temp6": "",
	"time7": "",
	"temp7": "",
	"time8": "",
	"temp8": "",
	"time9": "",
	"temp9": "",
	"time10": "",
	"temp10": ""
}, {
	"id": "c627c6eb.dbd8a8",
	"type": "mqtt-broker",
	"z": "cb9d9d67.14ab3",
	"broker": "192.168.0.32",
	"port": "1883",
	"clientid": "",
	"usetls": false,
	"compatmode": true,
	"keepalive": "60",
	"cleansession": true,
	"willTopic": "",
	"willQos": "0",
	"willPayload": "",
	"birthTopic": "",
	"birthQos": "0",
	"birthPayload": ""
}]
```

**Comment by maragelis** [comment]
Thanks your idea is great.

I was something on lines of .
The Homekit thermostat has 4 states (Off,Heat,Cool,Auto) 
When off no mater what temp the thermostat is at I want a false output from Status node. 
When Heat it would take into account the manual setting of say 21 degrees. (or what ever is set)
when Auto I can pass a profile and let the thermostat do its thing.

I know i can pass a very low setting when setting off like 10 degrees  this would be like off if someone sends a temp setting to homekit it will turn on no mater which setting its at.

One other thing, I would like your feed back on something, is it best to implement Hysteresis and get a temp sample every 30sec  or sample the room temp like every 15min without Hysteresis.

Thanks

**Comment by cflurin** [comment]
I didn't use the HomeKit service `Thermostat` yet, I'll have a look and maybe we can improve the ramp-thermostat in order to reduce programming in node-red.

In my case I have a temperature-sensor in every room and a corresponding  actuator for every heating-valve (floor heating). The Sensor sends the value every 15min, generally a floor heating is quite slow so I don't need the hysteresis-setting.

**Comment by maragelis** [comment]
Same here I have a pellet heater which is quite slow too.
