### ISSUE TITLE
Missing Mode information

### ISSUE THREAD

**Issue by Toshibass** [cflurin/node-red-contrib-ramp-thermostat#30]
Hi, I have just started using this node and its working fine however I have one big problem as follows ... I set up a profile and initiate it by setting topic to 'setProfile' & payload to 'office' and I can see under the node that profile / mode is set to 'office' have tested it and it works great,
If I setTarget manually that overrides the profile and I can see under the node that 'manual' is set.
But I cannot find a way to get that current mode into my flow like 'office' (auto) or 'manual' (override) without this mode information I cannot tell on my dashboard if the thermostat is following the profile or if the target temperature has been set manually and the thermostat is not following the profile, is it possible? am I missing something? or if not could I suggest this fundamental requirement be added ?

**Comment by cflurin** [comment]
Hi,

You can use the following (undocumented) topic, payload:

```
msg.topic: getProfile
msg.payload: actual
```

Output3 sends the `msg.payload.name` (profile name or manual).

Please, install version 0.8.2.

**Comment by Toshibass** [comment]
Perfect thanks
