### ISSUE TITLE
Number of profiles accepted

### ISSUE THREAD

**Issue by HaraldFranzen** [cflurin/node-red-contrib-ramp-thermostat#32]
Hi,

I use your ramp-thermostat to control the temperature in four rooms. Thank you for putting in all the effort to create it!

For each out of four rooms in a building, I have a profile that runs from 00:00 through 23:59. The one thermostat is used for each room, as it is controlled by MQTT input from temperature sensors that I have in each room. So, room #1 reports a temperature; the thermostat is passed profile 1 and the output of the thermostat is passed to the heating in room 1. This way, each room is controlled and all works perfectly.

The fifth profile is a "frost" profile, that is defined by two points: 00:00 5°C to 23:59 5°C
When I invoke this 5th profile, for each room as my MQTT-messages come in, the thermostat does nothing. There is no output on state, current or target and hence there is no output to the heating in that (or any) room.

If all the heatings are on, the temperatures well above 5°C and I invoke profile 5, the heating will remain on indefinitely as there is no output from the thermostat.

Is there a limit to the amount of profiles or what am I doing wrong?

Do not hesitate to ask for specific info that can help solve the issue.

Thanks!

**Comment by cflurin** [comment]
Hi,

> Is there a limit to the amount of profiles or what am I doing wrong?

No limit

It should work, please try to simplify your flow (inputs using inject nodes), export your flow and post it hier.

Note: to check if the flow format is correct, import the flow here back to your node-red editor.

**Comment by HaraldFranzen** [comment]
Thank you for your very rapid response!

I do apologize; it was a user error...

In the case of profile 5 (the "do not heat unless under 5°C) I was NOT passing the current temperature and hence the thermostat could not work...

My apologies again and thank you for all your work!

And stay safe!
