### ISSUE TITLE
Unable to change profile

### ISSUE THREAD

**Issue by sanoranpenguin** [cflurin/node-red-contrib-ramp-thermostat#34]
Having trouble being able to change a profile using the setprofile topic with a json object containing the new profile. My test flow looks like this:

[{"id":"2d5a8be6.4c308c","type":"tab","label":"Flow 3","disabled":false,"info":""},{"id":"924a5779.aa129","type":"function","z":"2d5a8be6.4c308c","name":"Override Summer ON Peak","func":"msg.topic= \"setProfile\";\nmsg.payload = {\n  \"name\": \"Summer ON Peak\",\n  \"points\": [{\n      \"00:00\":74\n  },{\n      \"09:00\":75\n  },{\n      \"12:30\":76\n  },{\n      \"13:45\":68\n  },{\n      \"13:59\":68\n  },{\n      \"14:00\":88\n  },{\n      \"16:00\":78\n  },{\n      \"20:00\":76\n  },{\n      \"21:30\":75\n  },{\n      \"23:59\":74\n}]};\nmsg.payload = Object.assign({}, msg.payload);\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":380,"y":120,"wires":[["7069f958.544e38","7f781651.f6639"]]},{"id":"7069f958.544e38","type":"ramp-thermostat","z":"2d5a8be6.4c308c","name":"","profile":"e77b3110.47ed28","hysteresisplus":"0","hysteresisminus":"0","x":730,"y":120,"wires":[["7f781651.f6639"],["7f781651.f6639"],["7f781651.f6639"]]},{"id":"7f781651.f6639","type":"debug","z":"2d5a8be6.4c308c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":890,"y":220,"wires":[]},{"id":"bf4b8028.39ffc8","type":"inject","z":"2d5a8be6.4c308c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":120,"y":120,"wires":[["924a5779.aa129"]]},{"id":"973d517b.632fc8","type":"inject","z":"2d5a8be6.4c308c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":120,"y":220,"wires":[["de8a620.358542"]]},{"id":"de8a620.358542","type":"function","z":"2d5a8be6.4c308c","name":"get Summer ON Peak Profile","func":"msg.topic= \"getProfile\"\nmsg.payload = \"Summer ON Peak\";\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":380,"y":220,"wires":[["7069f958.544e38","7f781651.f6639"]]},{"id":"e77b3110.47ed28","type":"profile","z":"","name":"Summer ON Peak","time1":"00:00","temp1":"74","time2":"09:00","temp2":"75","time3":"12:30","temp3":"76","time4":"13:45","temp4":"68","time5":"13:59","temp5":"68","time6":"14:00","temp6":"76","time7":"16:00","temp7":"78","time8":"20:00","temp8":"76","time9":"21:30","temp9":"75","time10":"23:59","temp10":"74"}]

**Comment by cflurin** [comment]
Please go to the node-red forum to get help
