### ISSUE TITLE
Feature: request set profile without point definition

### ISSUE THREAD

**Issue by lauffsh** [cflurin/node-red-contrib-ramp-thermostat#37]
With using a "setprofile" it seems (what I could read with my limited Json knowledge ) that always the profile-name and the Points need to be defined. 
like this...
{
    "name": "Test",
    "points": [
        {
            "00:00": 21
        },
...
        {
            "23:59": 21
        }
    ]
}
Would it be to have a possibility to specify just the profile like 
{
    "name": "Test",
 }

And the points are taken from the ramp_themostate node definition .. This would be much more convenient... 
many thanks

**Comment by cflurin** [comment]
Please read the doc, use this:

> msg.topic: setProfile
> msg.payload: profile-name

**Comment by lauffsh** [comment]
Maybey I make something wrong...
But for me, this results in an error 

"TypeError: Cannot read property 'm' of undefined"

![2021-03-19_17-49-56](https://user-images.githubusercontent.com/80065390/111815233-b886f600-88db-11eb-8c33-5684146581ba.jpg)

And if I do it like this : 
![2021-03-19_18-01-09_AsString](https://user-images.githubusercontent.com/80065390/111816631-5a5b1280-88dd-11eb-8db9-c81b95d60138.jpg)

I get the error
"SyntaxError: Unexpected token } in JSON at position 57"


Many thx  in advance

**Comment by cflurin** [comment]
This works for me:
![rampinject](https://user-images.githubusercontent.com/5056710/111823302-153ade80-88e5-11eb-8d22-77e66ca49dcc.PNG)

**Comment by cflurin** [comment]
ramp-thermostat Version ?

**Comment by lauffsh** [comment]
Version 0.8.3

I realized that you use the "edit inject node" but I'm using the "edit change node".. Does this make a difference? 

Seems that I'm lost.. Even with edit inject node and configured as above.. 
getting a "msg.topic undefined" error 

apologize that I'm asking these maybe newbie questions 

Really appreciate your help

**Comment by cflurin** [comment]
Please, goto the node-red forum and upload your flow, I'm sure you will get help in the forum.
