### ISSUE TITLE
A "generic" node based on this principle

### ISSUE THREAD

**Issue by marksev1** [cflurin/node-red-contrib-ramp-thermostat#4]
So I'd like to have also in addition to this very nice thermostat node, a node that would allow generic 1, 0 etc. message payloads.

While still being based on sensor input and doing the switching stuff on schedule like this node is doing. 

For example at start interval it would send 1 and at the end of the interval it would set 0 or vica-versa.

**Comment by cflurin** [comment]
try this flow:
![digital](https://cloud.githubusercontent.com/assets/5056710/19829684/96cff9d6-9de8-11e6-9e90-460b83bf7fd9.jpeg)

it use an   inject node to trigger (every 30 sec) the ramp-thermostat input and a profile to control the output.
- for each change 0 to 1 or 1 to 0 there are 2 points with the same time.
- with the change node the output true/false can be set to on/off.

``` javascript
[{"id":"423d215.13b62e","type":"ramp-thermostat","z":"cb9d9d67.14ab3","name":"scheduler","profile":"989d639d.f6e2f","hysteresisplus":0,"hysteresisminus":0,"x":240,"y":920,"wires":[["7752553f.34af9c"],[],[]]},{"id":"5292eca5.b958d4","type":"inject","z":"cb9d9d67.14ab3","name":"","topic":"","payload":"0.5","payloadType":"num","repeat":"30","crontab":"","once":true,"x":110,"y":920,"wires":[["423d215.13b62e"]]},{"id":"6481e567.09d98c","type":"debug","z":"cb9d9d67.14ab3","name":"","active":true,"console":"false","complete":"false","x":590,"y":920,"wires":[]},{"id":"7752553f.34af9c","type":"change","z":"cb9d9d67.14ab3","name":"","rules":[{"t":"change","p":"payload","pt":"msg","from":"true","fromt":"bool","to":"on","tot":"str"},{"t":"change","p":"payload","pt":"msg","from":"false","fromt":"bool","to":"off","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":420,"y":920,"wires":[["6481e567.09d98c"]]},{"id":"989d639d.f6e2f","type":"profile","z":"","name":"digital","time1":"00:00","temp1":"0","time2":"10:00","temp2":"0","time3":"10:00","temp3":"1","time4":"16:00","temp4":"1","time5":"16:00","temp5":"0","time6":"24:00","temp6":"0","time7":"","temp7":"","time8":"","temp8":"","time9":"","temp9":"","time10":"","temp10":""}]
```

**Comment by marksev1** [comment]
In older version of node-red this doesn't seem to work (it doesnt switch nothing always the same value)...Also in newer version there are some problems like msg : string [16]
target undefined

**Comment by cflurin** [comment]
@marksev1:
this is a warning, probably 24:00 undefined. Take a look at the README.

``` sh
A profile has at least 2 points and should typically start at 00:00 and end at 24:00.
```

did you changed the sample above? if yes, please upload your version.

You could also try to solve your "use case" just using the node-red nodes.
Then we can see, how to do it with a generic node like the ramp-thermostat.
The goal should be to replace so many nodes as possible by a contrib-node, otherwise it's not worth to develop a new node.

**Comment by marksev1** [comment]
`[{"id":"d804325a.7043d","type":"ramp-thermostat","z":"8f7edaf4.fc0d78","name":"scheduler","profile":"baca5ee8.d4901","x":1032,"y":3151,"wires":[["e091ba71.deb7b8"],[],[]]},{"id":"e329e785.164d08","type":"inject","z":"8f7edaf4.fc0d78","name":"","topic":"","payload":"0.5","payloadType":"num","repeat":"30","crontab":"","once":true,"x":902,"y":3151,"wires":[["d804325a.7043d"]]},{"id":"9960606.dcac1a","type":"debug","z":"8f7edaf4.fc0d78","name":"","active":true,"console":"false","complete":"false","x":1382,"y":3151,"wires":[]},{"id":"e091ba71.deb7b8","type":"change","z":"8f7edaf4.fc0d78","name":"","rules":[{"t":"change","p":"payload","pt":"msg","from":"true","fromt":"bool","to":"on","tot":"str"},{"t":"change","p":"payload","pt":"msg","from":"false","fromt":"bool","to":"off","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":1212,"y":3151,"wires":[["9960606.dcac1a"]]},{"id":"baca5ee8.d4901","type":"profile","z":"","name":"digital","time1":"00:00","temp1":"0","time2":"10:00","temp2":"0","time3":"15:32","temp3":"1","time4":"16:00","temp4":"1","time5":"21:44","temp5":"1","time6":"21:47","temp6":"1","time7":"23:44","temp7":"1","time8":"23:46","temp8":"0","time9":"24:00","temp9":"0","time10":"","temp10":""}][{"id":"d804325a.7043d","type":"ramp-thermostat","z":"8f7edaf4.fc0d78","name":"scheduler","profile":"baca5ee8.d4901","x":1032,"y":3151,"wires":[["e091ba71.deb7b8"],[],[]]},{"id":"e329e785.164d08","type":"inject","z":"8f7edaf4.fc0d78","name":"","topic":"","payload":"0.5","payloadType":"num","repeat":"30","crontab":"","once":true,"x":902,"y":3151,"wires":[["d804325a.7043d"]]},{"id":"9960606.dcac1a","type":"debug","z":"8f7edaf4.fc0d78","name":"","active":true,"console":"false","complete":"false","x":1382,"y":3151,"wires":[]},{"id":"e091ba71.deb7b8","type":"change","z":"8f7edaf4.fc0d78","name":"","rules":[{"t":"change","p":"payload","pt":"msg","from":"true","fromt":"bool","to":"on","tot":"str"},{"t":"change","p":"payload","pt":"msg","from":"false","fromt":"bool","to":"off","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":1212,"y":3151,"wires":[["9960606.dcac1a"]]},{"id":"baca5ee8.d4901","type":"profile","z":"","name":"digital","time1":"00:00","temp1":"0","time2":"10:00","temp2":"0","time3":"15:32","temp3":"1","time4":"16:00","temp4":"1","time5":"21:44","temp5":"1","time6":"21:47","temp6":"1","time7":"23:44","temp7":"1","time8":"23:46","temp8":"0","time9":"24:00","temp9":"0","time10":"","temp10":""}]`

This for example doesnt work.

**Comment by cflurin** [comment]
there  is an error in your json, please check here:
http://jsonlint.com/

which ramp-thermostat version are you using? 
node-red menu > manage palette > node-red-contrib-ramp-thermostat (should be 0.3.0)

**Comment by marksev1** [comment]
[{"id":"d804325a.7043d","type":"ramp-thermostat","z":"8f7edaf4.fc0d78","name":"scheduler","profile":"baca5ee8.d4901","x":1032,"y":3151,"wires":[["e091ba71.deb7b8"],[],[]]},{"id":"e329e785.164d08","type":"inject","z":"8f7edaf4.fc0d78","name":"","topic":"","payload":"0.5","payloadType":"num","repeat":"30","crontab":"","once":true,"x":902,"y":3151,"wires":[["d804325a.7043d"]]},{"id":"9960606.dcac1a","type":"debug","z":"8f7edaf4.fc0d78","name":"","active":true,"console":"false","complete":"false","x":1382,"y":3151,"wires":[]},{"id":"e091ba71.deb7b8","type":"change","z":"8f7edaf4.fc0d78","name":"","rules":[{"t":"change","p":"payload","pt":"msg","from":"true","fromt":"bool","to":"on","tot":"str"},{"t":"change","p":"payload","pt":"msg","from":"false","fromt":"bool","to":"off","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":1212,"y":3151,"wires":[["9960606.dcac1a"]]},{"id":"baca5ee8.d4901","type":"profile","z":"","name":"digital","time1":"00:00","temp1":"0","time2":"10:00","temp2":"0","time3":"15:32","temp3":"1","time4":"16:00","temp4":"1","time5":"21:44","temp5":"1","time6":"21:47","temp6":"1","time7":"23:44","temp7":"1","time8":"23:46","temp8":"0","time9":"24:00","temp9":"0","time10":"","temp10":""}]

This should be valid.... I'm using node-red v 0.14.3 so i don't see that option in the menu.

**Comment by cflurin** [comment]
I've imported your flow and had to set the Hysteresis [+] and Hysteresis [-] to 0 (number).
It works for me. Please check your profile settings and you should please read and understand what I wrote above:

``` sh
for each change 0 to 1 or 1 to 0 there are 2 points with the same time.
```

edit:
import my sample above and try again.

**Comment by marksev1** [comment]
I don't quite understand this so if I have 0 at 10.00 and 1 at 11.00 I have to again write after that 0 at 10.00 and 1 at 11.00?

Also I don't see hysteresis setting...

**Comment by cflurin** [comment]
import my sample in the second post above and take a look at the profile settings.

**Comment by marksev1** [comment]
Aha I see what i need to do :). But still I don't see the hysteresis setting...Nope still doesnt work..

**Comment by cflurin** [comment]
check the version in the file package.json

```
.node-red/node_modules/node-red-contrib-ramp-thermostat/package.json
```

search for `version`

**Comment by marksev1** [comment]
I don't have nothing in there because i installed it globally i guess..

**Comment by cflurin** [comment]
... search for the ramp-thermostat on your computer (raspberry?)

**Comment by marksev1** [comment]
msev@orangepipc:~$ npm view node-red-contrib-ramp-thermostat

{ name: 'node-red-contrib-ramp-thermostat',
  description: 'A Node-RED node that emulates a thermostat',
  'dist-tags': { latest: '0.3.0' },
  versions: [ '0.1.0', '0.1.1', '0.1.2', '0.2.0', '0.2.1', '0.3.0' ],
  maintainers: 'cflurin flurin.npm@gmail.com',
  time: 
   { modified: '2016-10-25T08:58:18.621Z',
     created: '2016-10-11T12:05:21.497Z',
     '0.1.0': '2016-10-11T12:05:21.497Z',
     '0.1.1': '2016-10-11T12:24:48.790Z',
     '0.1.2': '2016-10-12T12:29:26.133Z',
     '0.2.0': '2016-10-18T09:22:47.054Z',
     '0.2.1': '2016-10-19T10:59:18.389Z',
     '0.3.0': '2016-10-25T08:58:18.621Z' },
  keywords: [ 'node-red', 'thermostat', 'single room temperature control' ],
  readmeFilename: 'README.md',
  homepage: 'https://github.com/cflurin/node-red-contrib-ramp-thermostat#readme',
  repository: 
   { type: 'git',
     url: 'git+https://github.com/cflurin/node-red-contrib-ramp-thermostat.git' },
  author: 'cflurin',
  bugs: { url: 'https://github.com/cflurin/node-red-contrib-ramp-thermostat/issues' },
  version: '0.3.0',

Is this correct way to search?

**Comment by marksev1** [comment]
Ah no sorry i have too old version  node-red-contrib-ramp-thermostat@0.2.1

Sorry.

**Comment by cflurin** [comment]
on your computer not on npm!

```
/usr/lib/node_modules
```

or

```
/usr/local/lib/node_modules
```

**Comment by marksev1** [comment]
It works cflurin. Thanks! Sorry for my noobness of not having the proper version.

Thanks!

**Comment by cflurin** [comment]
Okay. It would be nice if you could explain what you are trying to do.
I'm still thinking about a `generic node`.

**Comment by marksev1** [comment]
Well just to have different profiles also for other devices (non thermostatic). The profile thing that you have is very appealing. Also to be able to send 1 or 0 to the device "manually" same way as you added for the temperature. So this is already implemented right...

**Comment by cflurin** [comment]
I put it to my todo list. Just now I'm working on another project.

**Comment by marksev1** [comment]
Cool thanks!
