### ISSUE TITLE
this json payload doesnt allow profile to be set or used - no error shown as far as I can see

### ISSUE THREAD

**Issue by johnkweber** [cflurin/node-red-contrib-ramp-thermostat#5]
{"name":"SmallPot","points":{"17:00":370.0,"18:00":1000.0,"19:00":1000.0,"22:00":1000.0,"23:00":561.0,"23:59":1000.0,"1:00":1000.0,"2:00":1000.0,"3:00":1000.0,"4:00":1000.0}}

is this correct or am I missing something? accordingto documenttion this should set a new profile. I also have this profile set up already in the system 

I am using this for a kiln controller using raspberry pi and a ktype thermocouple. the new profiles are fetched out of a mysql database.

[{"id":"2d90c986.4cd016","type":"rpi-gpio out","z":"14b04856.1d90b8","name":"","pin":"16","set":true,"level":"0","out":"out","x":759,"y":73,"wires":[]},{"id":"2c1f6017.80a42","type":"inject","z":"14b04856.1d90b8","name":"","topic":"setCurrent","payload":" ","payloadType":"str","repeat":"1","crontab":"","once":true,"x":114,"y":125,"wires":[["46d31477.387edc","ee88f7be.ccfd68"]]},{"id":"46d31477.387edc","type":"exec","z":"14b04856.1d90b8","command":"python /home/pi/python-spi/testspipython.py","addpay":true,"append":"","useSpawn":"","timer":"","name":"","x":234,"y":277.5,"wires":[["24a544fd.e4520c","b865c8ed.eab578"],[],[]]},{"id":"23411701.35c408","type":"switch","z":"14b04856.1d90b8","name":"","property":"payload","propertyType":"msg","rules":[{"t":"true"},{"t":"false"}],"checkall":"true","outputs":2,"x":321,"y":128,"wires":[["e9949060.7fba4"],["53a352af.1182ec"]]},{"id":"e9949060.7fba4","type":"trigger","z":"14b04856.1d90b8","op1":"1","op2":"1","op1type":"str","op2type":"str","duration":"1","extend":false,"units":"s","reset":"","name":"","x":480,"y":83,"wires":[["2d90c986.4cd016","6c395bf9.18a494","57333fbb.d7048"]]},{"id":"53a352af.1182ec","type":"trigger","z":"14b04856.1d90b8","op1":"0","op2":"0","op1type":"str","op2type":"str","duration":"1","extend":false,"units":"s","reset":"","name":"","x":478,"y":131,"wires":[["2d90c986.4cd016","6c395bf9.18a494","57333fbb.d7048"]]},{"id":"4203a3b3.01b9bc","type":"inject","z":"14b04856.1d90b8","name":"","topic":"","payload":"0","payloadType":"str","repeat":"","crontab":"","once":false,"x":479,"y":30,"wires":[["2d90c986.4cd016"]]},{"id":"aec7c366.b4a16","type":"inject","z":"14b04856.1d90b8","name":"","topic":"","payload":"1","payloadType":"str","repeat":"","crontab":"","once":false,"x":672,"y":20,"wires":[["2d90c986.4cd016"]]},{"id":"4ab4b05.415375","type":"ui_gauge","z":"14b04856.1d90b8","name":"","group":"b2c413d9.bbd4c","order":1,"width":"3","height":"3","gtype":"gage","title":"Current Kiln Temperature","label":"Degrees Celcius","format":"{{value}}","min":0,"max":"800","colors":["#00b500","#e6e600","#ca3838"],"x":730,"y":225,"wires":[]},{"id":"ee88f7be.ccfd68","type":"trigger","z":"14b04856.1d90b8","op1":"1","op2":"0","op1type":"str","op2type":"str","duration":"500","extend":false,"units":"ms","reset":"","name":"","x":110,"y":384,"wires":[["1a4a6581.96984a"]]},{"id":"1a4a6581.96984a","type":"rpi-gpio out","z":"14b04856.1d90b8","name":"","pin":"36","set":true,"level":"0","out":"out","x":319,"y":384,"wires":[]},{"id":"6c395bf9.18a494","type":"ui_switch","z":"14b04856.1d90b8","name":"Heater Relay","label":"Heater Relay","group":"b2c413d9.bbd4c","order":0,"width":0,"height":0,"passthru":true,"topic":"","style":"","onvalue":"1","onvalueType":"str","onicon":"","oncolor":"","offvalue":"0","offvalueType":"str","officon":"","offcolor":"","x":747,"y":132,"wires":[[]]},{"id":"57333fbb.d7048","type":"rpi-gpio out","z":"14b04856.1d90b8","name":"","pin":"38","set":true,"level":"0","out":"out","x":750,"y":171,"wires":[]},{"id":"aea6383b.ed8638","type":"rpi-gpio in","z":"14b04856.1d90b8","name":"","pin":"37","intype":"up","debounce":"25","read":false,"x":71,"y":558,"wires":[["9487bec0.fea62"]]},{"id":"9487bec0.fea62","type":"trigger","z":"14b04856.1d90b8","op1":" ","op2":" ","op1type":"str","op2type":"str","duration":"2","extend":false,"units":"min","reset":"","name":"","x":233,"y":549,"wires":[["b2fcba04.170588"]]},{"id":"b2fcba04.170588","type":"exec","z":"14b04856.1d90b8","command":"sudo shutdown -r now","addpay":true,"append":"","useSpawn":false,"timer":"","name":"","x":465,"y":591,"wires":[[],[],[]]},{"id":"49b6db8e.1de4b4","type":"tcp out","z":"14b04856.1d90b8","host":"localhost","port":"8888","beserver":"client","base64":false,"end":false,"name":"","x":782,"y":583,"wires":[]},{"id":"59fd2096.b6461","type":"exec","z":"14b04856.1d90b8","command":"python /home/pi/ssd1306/examples/tcpserver.py","addpay":true,"append":"","useSpawn":true,"timer":"","name":"","x":527,"y":698,"wires":[[],[],[]]},{"id":"b3e06b3d.d371c8","type":"inject","z":"14b04856.1d90b8","name":"","topic":"","payload":" ","payloadType":"str","repeat":"","crontab":"","once":true,"x":112,"y":683,"wires":[["59fd2096.b6461"]]},{"id":"b865c8ed.eab578","type":"ramp-thermostat","z":"14b04856.1d90b8","name":"","profile":"c62599b2.860ed8","hysteresisplus":"2.0","hysteresisminus":"2.0","x":444,"y":437.5,"wires":[["23411701.35c408","75c3be7d.7b3be"],["4ab4b05.415375","2cab72e7.84bcfe","ca705ef9.39ae8"],["b191a87d.4d5038","12f8f1e6.556fae","ca705ef9.39ae8"]]},{"id":"b191a87d.4d5038","type":"ui_gauge","z":"14b04856.1d90b8","name":"","group":"b2c413d9.bbd4c","order":1,"width":"3","height":"3","gtype":"gage","title":"Desired Kiln Temperature","label":"Degrees Celcius","format":"{{value}}","min":0,"max":"800","colors":["#00b500","#e6e600","#ca3838"],"x":730,"y":263,"wires":[]},{"id":"75c3be7d.7b3be","type":"debug","z":"14b04856.1d90b8","name":"","active":false,"console":"false","complete":"payload","x":728,"y":321,"wires":[]},{"id":"2cab72e7.84bcfe","type":"debug","z":"14b04856.1d90b8","name":"","active":false,"console":"false","complete":"false","x":751,"y":432,"wires":[]},{"id":"12f8f1e6.556fae","type":"debug","z":"14b04856.1d90b8","name":"","active":false,"console":"false","complete":"false","x":678,"y":496,"wires":[]},{"id":"5d8ce1e8.0519b","type":"mysql","z":"14b04856.1d90b8","mydb":"cbb54ffd.50a7","name":"","x":104,"y":990,"wires":[["2a059426.ad0d9c","ce53bb39.b70d38"]]},{"id":"ffcf183b.cbeae8","type":"debug","z":"14b04856.1d90b8","name":"output","active":false,"console":"false","complete":"payload","x":555,"y":776,"wires":[]},{"id":"8eb9084c.2cc1b8","type":"function","z":"14b04856.1d90b8","name":"timeConvert","func":"if ( !msg.timestamp ) msg.timestamp = Math.round(+new Date());\n\nvar dt = new Date(msg.timestamp);\nvar msg = \n\tdt.getHours();\n\nglobal.set(\"targettime\",msg);\nreturn msg;","outputs":1,"noerr":0,"x":351,"y":773,"wires":[["ffcf183b.cbeae8"]]},{"id":"138f5d7c.b37453","type":"inject","z":"14b04856.1d90b8","name":"Get Time","topic":"","payload":"","payloadType":"date","repeat":"60","crontab":"","once":true,"x":127,"y":765,"wires":[["8eb9084c.2cc1b8"]]},{"id":"ed845d6c.a47c7","type":"debug","z":"14b04856.1d90b8","name":"","active":false,"console":"false","complete":"true","x":443,"y":880,"wires":[]},{"id":"9d5ccda0.16831","type":"function","z":"14b04856.1d90b8","name":"","func":"var myTime = global.get(\"targettime\");\nmsg.topic = \"select temp from times where times like '\"+ myTime +\"%'\";\nreturn msg;","outputs":1,"noerr":0,"x":98,"y":935,"wires":[["5d8ce1e8.0519b"]]},{"id":"2a059426.ad0d9c","type":"function","z":"14b04856.1d90b8","name":"","func":"msg.topic = 'setTarget';\n\nreturn msg;","outputs":1,"noerr":0,"x":286,"y":984,"wires":[["d677ce1d.341be"]]},{"id":"24a544fd.e4520c","type":"debug","z":"14b04856.1d90b8","name":"","active":false,"console":"false","complete":"false","x":481,"y":197,"wires":[]},{"id":"d677ce1d.341be","type":"contrib-json","z":"14b04856.1d90b8","engine":"JSONSelect","command":"jq","expr":".temp","complete":"property","prop":"payload","name":"","x":294,"y":934,"wires":[["2def6ec6.308f22"]]},{"id":"2def6ec6.308f22","type":"function","z":"14b04856.1d90b8","name":"","func":"msg.payload = msg.payload.toString('utf8');\nreturn msg;","outputs":1,"noerr":0,"x":284,"y":884,"wires":[["ed845d6c.a47c7","b865c8ed.eab578"]]},{"id":"ce53bb39.b70d38","type":"debug","z":"14b04856.1d90b8","name":"","active":false,"console":"false","complete":"false","x":137,"y":1075,"wires":[]},{"id":"eda1f31f.73f87","type":"inject","z":"14b04856.1d90b8","name":"","topic":"","payload":"","payloadType":"str","repeat":"5","crontab":"","once":true,"x":96,"y":861,"wires":[[]]},{"id":"96ac6db4.38b8d","type":"exec","z":"14b04856.1d90b8","command":"php /var/www/html/scripts/setprofile.php","addpay":true,"append":"","useSpawn":true,"timer":"","name":"","x":381,"y":1220,"wires":[["8ad34b19.cfd0d8"],[],[]]},{"id":"975264b0.5c93f8","type":"inject","z":"14b04856.1d90b8","name":"","topic":"","payload":" ","payloadType":"str","repeat":"5","crontab":"","once":true,"x":107,"y":1207,"wires":[[]]},{"id":"8ad34b19.cfd0d8","type":"debug","z":"14b04856.1d90b8","name":"","active":true,"console":"false","complete":"false","x":672,"y":1210,"wires":[]},{"id":"ca705ef9.39ae8","type":"join","z":"14b04856.1d90b8","name":"","mode":"custom","build":"string","property":"payload","propertyType":"msg","key":"topic","joiner":"->","timeout":"","count":"2","x":697,"y":373,"wires":[["49b6db8e.1de4b4"]]},{"id":"b2c413d9.bbd4c","type":"ui_group","z":"14b04856.1d90b8","name":"Default","tab":"91c10b53.4bedd8","disp":true,"width":"6"},{"id":"c62599b2.860ed8","type":"profile","z":"14b04856.1d90b8","name":"SmallPot","time1":"18:00","temp1":"200.0","time2":"18:25","temp2":"400","time3":"18:39","temp3":"900","time4":"17:00","temp4":"30.0","time5":"19:00","temp5":"45.0","time6":"","temp6":"","time7":"","temp7":"","time8":"","temp8":"","time9":"","temp9":"","time10":"","temp10":""},{"id":"cbb54ffd.50a7","type":"MySQLdatabase","z":"14b04856.1d90b8","host":"127.0.0.1","port":"3306","db":"kilncontroller","tz":""},{"id":"91c10b53.4bedd8","type":"ui_tab","z":"14b04856.1d90b8","name":"Home","icon":"dashboard"}]

**Comment by cflurin** [comment]
Hi,
I apologize for the long delay. I didn't get a notification or an email from GitHub.
If this issue still persists, would you please reduce your flow so far as possible and export the flow concerning this issue, so I can import your flow.

**Comment by cflurin** [comment]
Closing for now, you can open a new issue if you need support.
