### ISSUE TITLE
Optional field to define duration of target override

### ISSUE THREAD

**Issue by waako** [cflurin/node-red-contrib-ramp-thermostat#6]
Feature request to have optional field where you can set how long you want the target temperature override to run for.
So idea would be:
* Profile `<select>`
* Hysteresis [+] `<input>`
* Hysteresis [-] `<input>`
* Override duration `<input>` *(optional) minutes until return to profile target*

In an ideal world I need to work out how to expose that setting to the dashboard so target can be manually set and for a chosen amount of time.

I'm currently playing with this node and [Nest like dashboard thermostat](https://github.com/Paul-Reed/thermostat).
For now it just reflects the state of heating, with similar target temperatures and override target temp, not actually controlling the heating, but it's fun planning it out.

**Comment by cflurin** [comment]
Try this flow:
```sh
[{"id":"6e0b3217.82627c","type":"ramp-thermostat","z":"6da90f72.dff58","name":"","profile":"456075b4.05240c","hysteresisplus":0,"hysteresisminus":0,"x":590,"y":260,"wires":[[],[],[]]},{"id":"9fbf2f78.079ec","type":"inject","z":"6da90f72.dff58","name":"","topic":"setTarget","payload":"21.0","payloadType":"num","repeat":"","crontab":"","once":false,"x":210,"y":260,"wires":[["6e0b3217.82627c","b045b317.2cb89"]]},{"id":"b045b317.2cb89","type":"delay","z":"6da90f72.dff58","name":"","pauseType":"delay","timeout":"1","timeoutUnits":"minutes","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":220,"y":340,"wires":[["c447dcee.5dd9e"]]},{"id":"c447dcee.5dd9e","type":"function","z":"6da90f72.dff58","name":"setProfile to default","func":"msg.topic = \"setProfile\";\nmsg.payload = \"default\";\nreturn msg;","outputs":1,"noerr":0,"x":390,"y":340,"wires":[["6e0b3217.82627c"]]},{"id":"456075b4.05240c","type":"profile","z":"","name":"standard","time1":"00:00","temp1":"16.0","time2":"04:00","temp2":"16.0","time3":"08:00","temp3":"20.0","time4":"19:00","temp4":"20.0","time5":"20:00","temp5":"16.0","time6":"24:00","temp6":"16.0","time7":"","temp7":"","time8":"","temp8":"","time9":"","temp9":"","time10":"","temp10":""}]
```

It set the Target to 21.0 and at the same time starts a delay (timer) which at the end will set the Profile to the default Profile.

**Comment by waako** [comment]
Oh sweet thanks, that'll do the job for now.

**Comment by cflurin** [comment]
Okay, closing for now.

**Comment by smadds** [comment]
It would be really helpful if the thermostat could be configured to cancel the manual override at the next profile time - this would mimic how many home central heating controllers work - and would ensure the normal routine was returned to in time.

**Comment by cflurin** [comment]
What do you mean by "at the next profile time"?

**Comment by smadds** [comment]
the profiles consist of a list of times and temperatures, so when the next defined time occurs, option to switch back to auto (=current profile) then.

It would also be great to have the profile temperature changes on a separate output - this would allow us to inject a set-profile.
