### ISSUE TITLE
why not compliate

### ISSUE THREAD

**Issue by eevural** [cflurin/node-red-contrib-ramp-thermostat#9]
[{"id":"6caf7411.04304c","type":"inject","z":"d08c2ef7.36a82","name":"","topic":"","payload":"1","payloadType":"num","repeat":"","crontab":"","once":false,"x":354.93748474121094,"y":490.96875,"wires":[["2e190ddf.9af742"]]}]

why thermostat can not read dth22 

dth22 send to 22.5 but thermostad error messsage msg.topic undefined

**Comment by cflurin** [comment]
msg.topic must be empty "" or "setCurrent"
